#2Files/src/com/neuralt/smp/client/web/controller/SetClockController.java
package com.neuralt.smp.client.web.controller;

import java.io.Serializable;
import java.net.MalformedURLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.event.ValueChangeEvent;

import org.primefaces.component.selectbooleancheckbox.SelectBooleanCheckbox;
import org.primefaces.model.DefaultTreeNode;
import org.primefaces.model.TreeNode;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.neuralt.smp.AgentRuntimeException;
import com.neuralt.smp.client.MonitoredEntity;
import com.neuralt.smp.client.MonitoredHost;
import com.neuralt.smp.client.MonitoredHost.HostStatus;
import com.neuralt.smp.client.MonitoredSystem;
import com.neuralt.smp.client.SmpClient;
import com.neuralt.smp.client.web.MessageKey;
import com.neuralt.smp.client.web.SelectedMonitoredHost;
import com.neuralt.smp.client.web.SelectedMonitoredSystem;
import com.neuralt.smp.client.web.security.AuditLogger;
import com.neuralt.smp.client.web.security.AuditTrailLog.ActionType;
import com.neuralt.smp.client.web.security.ScreenType;
import com.neuralt.smp.util.StringUtil;
import com.neuralt.web.util.CssStyleUtil;
import com.neuralt.web.util.jsf.LocaleMessages;
import com.neuralt.web.util.jsf.WebUtil;

@ManagedBean
@ViewScoped
public class SetClockController implements Serializable {
	private static final long serialVersionUID = -453928492519225646L;
	private static final Logger logger = LoggerFactory
			.getLogger(SetClockController.class);
	private List<MonitoredHost> hosts;
	private Map<MonitoredHost, String> feedbacks;
	private Map<SelectedMonitoredSystem, MonitoredSystem> sysMap;
	private Map<SelectedMonitoredHost, MonitoredHost> hostMap;
	private TreeNode entityRoot;
	private Date time;

	public SetClockController() {
		feedbacks = new HashMap<MonitoredHost, String>();
		hostMap = new HashMap<SelectedMonitoredHost, MonitoredHost>();
		hosts = new ArrayList<MonitoredHost>();
		createTreeTableModel();
	}

	private void createTreeTableModel() {
		entityRoot = new DefaultTreeNode("root", null);
		entityRoot.setExpanded(true);

		for (MonitoredSystem sys : SmpClient.instance.getSystems()) {
			SelectedMonitoredSystem selectedSys = new SelectedMonitoredSystem(
					sys);
			TreeNode sysNode = new DefaultTreeNode(selectedSys, entityRoot);
			sysNode.setExpanded(true);
			for (MonitoredHost host : sys.getHosts()) {
				SelectedMonitoredHost selectedHost = null;
				try {
					selectedHost = new SelectedMonitoredHost(host);
				} catch (MalformedURLException e) {
				}
				if (host.getConfig().isAgentDeployed()) {
					TreeNode hostNode = new DefaultTreeNode(selectedHost,
							sysNode);
					hostNode.setExpanded(true);
					hostMap.put(selectedHost, host);
					// testing purpose
					// hosts.add(host);

				}
			}
		}
	}

	public String displayStatus(MonitoredEntity entity) {
		if (entity instanceof SelectedMonitoredHost) {
			SelectedMonitoredHost selectedHost = (SelectedMonitoredHost) entity;
			return hostMap.get(selectedHost).getStatusText();
		}
		return "";
	}

	public boolean check(MonitoredEntity entity) {
		if (entity instanceof MonitoredHost) {
			MonitoredHost host = (MonitoredHost) entity;
			if (hosts.contains(host)) {
				hosts.remove(host);
			} else {
				hosts.add(host);
			}
		}

		return false;
	}

	public void setClock() {

		String timeStr = StringUtil.convertTimeFormat(time);
		logger.debug("time set:" + timeStr);
		feedbacks = new HashMap<MonitoredHost, String>();
		for (SelectedMonitoredHost host : hostMap.keySet()) {
			if (host.isSelected()) {
				if (displayStatus(host).equals(HostStatus.DISCONNECTED.name()))
					feedbacks.put(host, host.getStatusText());
				else {
					try {
						feedbacks.put(host, SmpClient.instance.setClock(host
								.getSys().getName(),
								host.getConfig().getName(), timeStr));
						AuditLogger.logAuditTrail(ScreenType.COMMAND,
								WebUtil.getRequestPath(), ActionType.COMMAND,
								"set-clock", host.getConfig().getName() + ": "
										+ timeStr);
					} catch (AgentRuntimeException ignore) {
						// should ignore
						WebUtil.addMessage(FacesMessage.SEVERITY_ERROR,
								MessageKey.GENERAL_ERROR,
								LocaleMessages.getString(
										MessageKey.CLOCK_SYNC_CONNECT_FAILED,
										host.getName()));
					}
				}
			}
		}
	}

	public String feedback(MonitoredEntity entity) {
		if (entity instanceof MonitoredSystem) {
			return "";
		} else {
			return feedbacks.get(entity);
		}
	}

	public String getStatusCssClass(String statusText) {
		String result = CssStyleUtil.getStatusCssClass(statusText);
		if (result == null)
			result = "";

		return result;
	}

	public void checkBoxListener(ValueChangeEvent event) {
		SelectBooleanCheckbox sbc = (SelectBooleanCheckbox) event
				.getComponent();
	}

	public boolean isHost(MonitoredEntity entity) {
		return (entity instanceof MonitoredHost);
	}

	public List<MonitoredHost> getHosts() {
		return hosts;
	}

	public void setHosts(List<MonitoredHost> hosts) {
		this.hosts = hosts;
	}

	public Map<MonitoredHost, String> getFeedbacks() {
		return feedbacks;
	}

	public void setFeedbacks(Map<MonitoredHost, String> feedbacks) {
		this.feedbacks = feedbacks;
	}

	public TreeNode getEntityRoot() {
		return entityRoot;
	}

	public void setEntityRoot(TreeNode entityRoot) {
		this.entityRoot = entityRoot;
	}

	public Date getTime() {
		return time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

}

#2Files/src/com/neuralt/web/util/jsf/SessionBean.java
package com.neuralt.web.util.jsf;

import java.io.Serializable;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIInput;
import javax.faces.context.FacesContext;
import javax.faces.event.AjaxBehaviorEvent;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.neuralt.smp.client.web.AppConfig;

@ManagedBean(name = "sessionBean")
@SessionScoped
public class SessionBean implements Serializable {
	private static final long serialVersionUID = -4376158576986654972L;
	private static final Map<String, String> localeMap;
	private String locale;
	private static final Logger logger = LoggerFactory
			.getLogger(SessionBean.class);

	private String sessionid;

	static {
		localeMap = new HashMap<String, String>();
		localeMap.put("中文", "zh_TW");
		localeMap.put("English", "en");
	}

	public boolean isInSession() {
		return sessionid != null;
	}

	public SessionBean() {
		Locale defaultLocale = FacesContext.getCurrentInstance()
				.getApplication().getDefaultLocale();
		if (defaultLocale.getCountry() != null
				&& defaultLocale.getCountry().length() > 0)
			locale = defaultLocale.getLanguage() + "_"
					+ defaultLocale.getCountry();
		else
			locale = defaultLocale.getLanguage();

	}

	public void countryLocaleCodeChanged(AjaxBehaviorEvent e) {
		logger.debug("Backing bean action listener: countryLocaleCodeChanged(valueChangeEvent)");

		// locale = e.getNewValue().toString();
		UIInput input = (UIInput) e.getComponent();
		locale = (String) input.getValue();
		FacesContext.getCurrentInstance().renderResponse();
	}

	public String getLocale() {
		return locale;
	}

	public void setLocale(String locale) {
		this.locale = locale;
	}

	public Map<String, String> getLocaleMap() {
		return localeMap;
	}

	public String getWebDateFormat() {
		return AppConfig.getWebDateFormat();
	}
}

#2Files/WebContent/pages/commands/setclock.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
   xmlns:ui="http://java.sun.com/jsf/facelets"
   	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://java.sun.com/jsf/html"
   template="/templates/master.xhtml">
   
  <ui:define name="title"> 
		#{msg['main.title']}          
  </ui:define>
  
  <ui:define name="content">	
  	<h:form id="mainForm">
  		<p:growl id="growl" globalOnly="true" autoUpdate="true"/>  		
		
		<p:panel id="pnlBrowse">
	    	<p:treeTable id="tblSys" widgetVar="systemTable"
	    			 value="#{setClockController.entityRoot}" var="entity" 
	    			 selection="#{setClockController.hosts}">
	    		<p:column>
	    			<f:facet name="header">Name</f:facet>
	    			<h:outputText value="#{entity.displayableName}" />
	    		</p:column>
	    		<p:column>
	    			<f:facet name="header">Description</f:facet>
	    			<h:outputText value="#{entity.description}" />
	    		</p:column>
	    		<p:column>
	    			<f:facet name="header">Type</f:facet>
	    			<h:outputText value="#{entity.entityType}" />
	    		</p:column>
	    		<p:column>
	    			<f:facet name="header">Status</f:facet>
	    			<h:outputText value="#{setClockController.displayStatus(entity)}" 
	    					styleClass="#{setClockController.getStatusCssClass(setClockController.displayStatus(entity))}" />
	    		</p:column>
	    		<p:column>
	    			<f:facet name="header">Feedback</f:facet>
	    			<h:outputText value="#{setClockController.feedback(entity)}" />
	    		</p:column>
	    		<p:column>
	    			<p:selectBooleanCheckbox value="#{entity.selected}" rendered="#{setClockController.isHost(entity)}"/>  
	    		</p:column>
	    	</p:treeTable>
	    	
	    </p:panel>
	    <p/>
		<p:panel >
			<p:panelGrid columns="1" >  
			    <f:facet name="header">  
			        #{msg['clock.sync.header']}  
			    </f:facet>
			    <p:calendar value="#{setClockController.time}" pattern="#{sessionBean.webDateFormat}" id="time" showButtonPanel="true">
	            </p:calendar>	
			    <f:facet name="footer">  
			        <p:commandButton type="submit" value="#{msg['clock.sync.button']}" icon="ui-icon-check" 
			        style="margin:0" action="#{setClockController.setClock}" update="tblSys"
			        rendered="#{UserBean.accessLevel=='WRITE'}"/>
			        <p:commandButton type="submit" value="#{msg['general.refresh']}" icon="ui-icon-arrowrefresh-1-s"
			        style="margin:0 position:absolute right:0px" action="setclock?faces-redirect=true"/>    
			    </f:facet>  
			</p:panelGrid>
		
		</p:panel>
		
  	</h:form>
  </ui:define>    
</ui:composition>

#2Files/WebContent/pages/commands/snmpquery.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui" xmlns:h="http://java.sun.com/jsf/html" template="/templates/master.xhtml">
	<ui:define name="title"> 
		#{msg['main.title']} - #{msg['snmp.title']}
	</ui:define>
	<ui:define name="pageTitle">
		#{msg['snmp.title']}
	</ui:define>

	<ui:define name="content">
		<h:form id="mainForm">
			<p:growl id="growl" showDetail="true" globalOnly="false" autoUpdate="true" />
			<p:layout style="height:750px;margin-right: 2px;" id="layout">

				<p:layoutUnit position="west" minSize="100" resizable="true"  collapsible="true" header="#{msg['snmp.config.list']}" size="340">
					<p:panel rendered="#{snmpBrowseController.snmpRoot!=null and !snmpBrowseController.snmpRoot.leaf}">
						<p:treeTable id="snmpConfig_treetbl_id" widgetVar="snmpConfig_treetbl" value="#{snmpBrowseController.snmpRoot}" var="entity"
							selectionMode="single" selection="#{snmpBrowseController.selectedSnmpNode}">
							<p:ajax event="select" listener="#{snmpBrowseController.onSnmpNodeSelected}" update=":mainForm:pnl_holder, :mainForm:oid_tree" />
							<p:column style="white-space:nowrap; width:230px">
								<f:facet name="header">
									#{msg['general.name']}
								</f:facet>
								<h:outputText value="#{entity.name}" />
							</p:column>
							<p:column style="white-space:nowrap; width:160px">
								<f:facet name="header">
									#{msg['general.type']}
								</f:facet>
								<h:outputText value="#{entity.entityType}" />
							</p:column>
						</p:treeTable>
					</p:panel>
										
					<p:panel rendered="#{snmpBrowseController.snmpRoot == null || snmpBrowseController.snmpRoot.leaf}">
						<p:outputLabel escape="false" value="#{msg['snmp.query.snmpagent.addnew']}"  style="font-style: italic;"/>
					</p:panel>
				</p:layoutUnit>

				<p:layoutUnit id="center_layout" position="center" header="#{msg['snmp.query.header.resultTable']}" size="2000px">
					<p:outputPanel id="pnl_holder">
						<p:panel id="detail_pnl" header="#{snmpBrowseController.header}" rendered="#{snmpBrowseController.oidNodeSelected}">
							<p:commandButton value="#{msg['snmp.walk']}" action="#{snmpBrowseController.query}" update="result_holder"
								disabled="#{!snmpBrowseController.snmpConfigSelected}">
							</p:commandButton>
							<p />
							<p:outputPanel id="result_holder">
								<p:dataTable value="#{snmpBrowseController.results}" var="result">
									<p:column style="width:300px">
										<f:facet name="header">
											<h:outputText value="#{msg['snmp.object']}" />
										</f:facet>
										<h:outputText value="#{snmpBrowseController.getTranslatedOid(result.oid)}" />
									</p:column>
									<p:column style="width:200px">
										<f:facet name="header">
											<h:outputText value="#{msg['snmp.value']}" />
										</f:facet>
										<h:outputText value="#{result.name}" />
									</p:column>
								</p:dataTable>
							</p:outputPanel>
						</p:panel>
						
						<p:panel rendered="#{!snmpBrowseController.oidNodeSelected}">
							<p:outputLabel value="#{msg['snmp.query.empty.noresult.step1']}" style="font-style: italic;"/>
							<br/>
							<p:outputLabel value="#{msg['snmp.query.empty.noresult.step2']}" style="font-style: italic;"/>
						</p:panel>
					</p:outputPanel>
				</p:layoutUnit>
				<p:layoutUnit position="east" minSize="100" resizable="true" collapsible="true" header="#{msg['snmp.query.oid.list.header']}" size="340">
					<p:outputPanel id="oid_tree" >
						<p:tree value="#{snmpBrowseController.oidRoot}" var="trap" animate="true" selectionMode="single"
							selection="#{snmpBrowseController.selectedOidNode}" style="width:99%"
							rendered="#{snmpBrowseController.oidRoot!=null and !snmpBrowseController.oidRoot.leaf}">
							<p:ajax event="select" update=":mainForm:pnl_holder" listener="#{snmpBrowseController.onOidNodeSelected}" />
							<p:treeNode expandedIcon="ui-icon-folder-open" collapsedIcon="ui-icon-folder-collapsed">
								<h:outputText value="#{trap.name}" />
							</p:treeNode>
						</p:tree>
	
						<p:panel rendered="#{snmpBrowseController.oidRoot!=null and snmpBrowseController.oidRoot.leaf}">
							<p:outputLabel escape="false" value="#{msg['snmp.query.mib.addnew']}" style="font-style: italic;"/>
						</p:panel>
	
						<p:panel rendered="#{snmpBrowseController.oidRoot==null}">
							<p:outputLabel escape="false" value="#{msg['snmp.query.mib.snmpagent.notselected']}" style="font-style: italic;"/>
						</p:panel>
					</p:outputPanel>
				</p:layoutUnit>
			</p:layout>
		</h:form>
	</ui:define>
</ui:composition>